### ISSUE TITLE
Objects (Controlled, Inanimate, Animate)

### ISSUE THREAD

**Issue by Exegetech** [computergraphicsclub/game#2]
- [x] Setting 2D objects onto stage (e.g. squares) https://github.com/computergraphicsclub/game/commit/8f3e7deb40579f620928abe1526953642f6439d8
- [ ] Placing 3D objects into game (e.g. cubes)

**Comment by Exegetech** [comment]
@GitableRoy is everything done in this issue?

**Comment by GitableRoy** [comment]
@christiansakai Placing 3D objects with ThreeJS still needs to be looked into

**Comment by Exegetech** [comment]
Added `three` and `lodash` npm package to help.

https://github.com/computergraphicsclub/game/commit/c4ffd01ebe8ca60cc5daaf00766770c872f338df
